export const dummyJson = [
    {
      matchID: 20,
      matchPercentage: "70%",
      maleName: "Oliver",
      femaleName: "Sophie",
    },
    {
      matchID: 22,
      matchPercentage: "74%",
      maleName: "Oliver",
      femaleName: "Lily",
    },
    {
      matchID: 23,
      matchPercentage: "80%",
      maleName: "Oliver",
      femaleName: "Rebbeca",
    },
    {
      matchID: 24,
      matchPercentage: "90%",
      maleName: "Oliver",
      femaleName: "Naila",
    },
    {
      matchID: 25,
      matchPercentage: "82%",
      maleName: "William",
      femaleName: "Sophie",
    },
    {
      matchID: 26,
      matchPercentage: "76%",
      maleName: "William",
      femaleName: "Lily",
    },
    {
      matchID: 27,
      matchPercentage: "88%",
      maleName: "William",
      femaleName: "Rebbeca",
    },
    {
      matchID: 28,
      matchPercentage: "77%",
      maleName: "William",
      femaleName: "Naila",
    },
    {
      matchID: 29,
      matchPercentage: "91%",
      maleName: "William",
      femaleName: "Naveera",
    },
    {
      matchID: 30,
      matchPercentage: "95%",
      maleName: "Naoh",
      femaleName: "Sophie",
    },
    {
      matchID: 31,
      matchPercentage: "93%",
      maleName: "Naoh",
      femaleName: "Lily",
    },
    {
      matchID: 32,
      matchPercentage: "83%",
      maleName: "Naoh",
      femaleName: "Rebbeca",
    },
    {
      matchID: 33,
      matchPercentage: "89%",
      maleName: "Naoh",
      femaleName: "Naila",
    },
    {
      matchID: 34,
      matchPercentage: "78%",
      maleName: "Naoh",
      femaleName: "Naveera",
    },
    {
      matchID: 35,
      matchPercentage: "92%",
      maleName: "Issac",
      femaleName: "Sophie",
    },
    {
      matchID: 36,
      matchPercentage: "81%",
      maleName: "Issac",
      femaleName: "Lily",
    },
    {
      matchID: 37,
      matchPercentage: "75%",
      maleName: "Issac",
      femaleName: "Rebbeca",
    },
    {
      matchID: 38,
      matchPercentage: "86%",
      maleName: "Issac",
      femaleName: "Naila",
    },
    {
      matchID: 39,
      matchPercentage: "94%",
      maleName: "Issac",
      femaleName: "Naveera",
    },
    {
      matchID: 40,
      matchPercentage: "73%",
      maleName: "Elba",
      femaleName: "Sophie",
    },
    {
      matchID: 41,
      matchPercentage: "87%",
      maleName: "Elba",
      femaleName: "Lily",
    },
    {
      matchID: 42,
      matchPercentage: "79%",
      maleName: "Elba",
      femaleName: "Rebbeca",
    },
    {
      matchID: 43,
      matchPercentage: "84%",
      maleName: "Elba",
      femaleName: "Naila",
    },
    {
      matchID: 44,
      matchPercentage: "72%",
      maleName: "Elba",
      femaleName: "Naveera",
    },
    {
      matchID: 45,
      matchPercentage: "70%",
      maleName: "Oliver",
      femaleName: "Nadia",
    },
    {
      matchID: 46,
      matchPercentage: "70%",
      maleName: "Oliver",
      femaleName: "Lucy",
    },
    {
      matchID: 47,
      matchPercentage: "70%",
      maleName: "Oliver",
      femaleName: "Karen",
    },
    {
      matchID: 48,
      matchPercentage: "70%",
      maleName: "Oliver",
      femaleName: "Ameila",
    },
    {
      matchID: 49,
      matchPercentage: "70%",
      maleName: "William",
      femaleName: "Nadia",
    },
    {
      matchID: 50,
      matchPercentage: "70%",
      maleName: "William",
      femaleName: "Lucy",
    },
    {
      matchID: 51,
      matchPercentage: "70%",
      maleName: "William",
      femaleName: "Karen",
    },
    {
      matchID: 52,
      matchPercentage: "70%",
      maleName: "William",
      femaleName: "Ameila",
    },
    {
      matchID: 53,
      matchPercentage: "70%",
      maleName: "Naoh",
      femaleName: "Nadia",
    },
    {
      matchID: 54,
      matchPercentage: "70%",
      maleName: "Naoh",
      femaleName: "Lucy",
    },
    {
      matchID: 55,
      matchPercentage: "70%",
      maleName: "Naoh",
      femaleName: "Karen",
    },
    {
      matchID: 56,
      matchPercentage: "70%",
      maleName: "Naoh",
      femaleName: "Ameila",
    },
    {
      matchID: 57,
      matchPercentage: "70%",
      maleName: "Issac",
      femaleName: "Nadia",
    },
    {
      matchID: 58,
      matchPercentage: "70%",
      maleName: "Issac",
      femaleName: "Lucy",
    },
    {
      matchID: 59,
      matchPercentage: "70%",
      maleName: "Issac",
      femaleName: "Karen",
    },
    {
      matchID: 60,
      matchPercentage: "70%",
      maleName: "Issac",
      femaleName: "Ameila",
    },
    {
      matchID: 61,
      matchPercentage: "70%",
      maleName: "Elba",
      femaleName: "Nadia",
    },
    {
      matchID: 62,
      matchPercentage: "70%",
      maleName: "Elba",
      femaleName: "Lucy",
    },
    {
      matchID: 63,
      matchPercentage: "70%",
      maleName: "Elba",
      femaleName: "Karen",
    },
    {
      matchID: 64,
      matchPercentage: "70%",
      maleName: "Elba",
      femaleName: "Ameila",
    },
    {
      matchID: 65,
      matchPercentage: "70%",
      maleName: "Joseph",
      femaleName: "Sophie",
    },
    {
      matchID: 66,
      matchPercentage: "74%",
      maleName: "Joseph",
      femaleName: "Lily",
    },
    {
      matchID: 67,
      matchPercentage: "80%",
      maleName: "Joseph",
      femaleName: "Rebbeca",
    },
    {
      matchID: 68,
      matchPercentage: "90%",
      maleName: "Joseph",
      femaleName: "Naila",
    },
    {
      matchID: 91,
      matchPercentage: "76%",
      maleName: "Joseph",
      femaleName: "Naveera",
    },
    {
      matchID: 69,
      matchPercentage: "82%",
      maleName: "Jack",
      femaleName: "Sophie",
    },
    {
      matchID: 70,
      matchPercentage: "76%",
      maleName: "Jack",
      femaleName: "Lily",
    },
    {
      matchID: 71,
      matchPercentage: "88%",
      maleName: "Jack",
      femaleName: "Rebbeca",
    },
    {
      matchID: 72,
      matchPercentage: "77%",
      maleName: "Jack",
      femaleName: "Naila",
    },
    {
      matchID: 73,
      matchPercentage: "78%",
      maleName: "Jack",
      femaleName: "Naveera",
    },
    {
      matchID: 74,
      matchPercentage: "95%",
      maleName: "David",
      femaleName: "Sophie",
    },
    {
      matchID: 75,
      matchPercentage: "93%",
      maleName: "David",
      femaleName: "Lily",
    },
    {
      matchID: 76,
      matchPercentage: "83%",
      maleName: "David",
      femaleName: "Rebbeca",
    },
    {
      matchID: 77,
      matchPercentage: "89%",
      maleName: "David",
      femaleName: "Naila",
    },
    {
      matchID: 78,
      matchPercentage: "87%",
      maleName: "David",
      femaleName: "Naveera",
    },
    {
      matchID: 79,
      matchPercentage: "92%",
      maleName: "Issac",
      femaleName: "Sophie",
    },
    {
      matchID: 80,
      matchPercentage: "81%",
      maleName: "James",
      femaleName: "Lily",
    },
    {
      matchID: 81,
      matchPercentage: "75%",
      maleName: "Issac",
      femaleName: "Rebbeca",
    },
    {
      matchID: 82,
      matchPercentage: "86%",
      maleName: "Issac",
      femaleName: "Naila",
    },
    {
      matchID: 83,
      matchPercentage: "91%",
      maleName: "Issac",
      femaleName: "Naveera",
    },
    {
      matchID: 84,
      matchPercentage: "73%",
      maleName: "Elba",
      femaleName: "Sophie",
    },
    {
      matchID: 85,
      matchPercentage: "87%",
      maleName: "Elba",
      femaleName: "Lily",
    },
    {
      matchID: 86,
      matchPercentage: "79%",
      maleName: "Elba",
      femaleName: "Rebbeca",
    },
    {
      matchID: 87,
      matchPercentage: "84%",
      maleName: "Elba",
      femaleName: "Naila",
    },
    {
      matchID: 88,
      matchPercentage: "72%",
      maleName: "Elba",
      femaleName: "Naveera",
    },
  ];
  